services:
  php:
    build:
      context: docker/php/8_2
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        USER_NAME: ${USER_NAME}
    container_name: symfony_api_php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - net

  web:
    image: nginx:latest
    container_name: symfony_api_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - net

networks:
  net:
    external: true